application: rakkyo-works 

version: 1

runtime: python

api_version: 1


handlers:
- url: /stylesheets
  static_dir: view/stylesheets
- url: /images 
  static_dir: view/images
- url: /script
  static_dir: view/script
- url: /script
  static_dir: com/gae/script
- url: /script
  static_dir: META-INF/script
- url: /.*
  script: main.py
